export type {
  ErrorCollectorConfig,
  ErrorSnapshot,
  EventSnapshot,
  MemoryInfo,
  Monitor,
  MonitorConfig,
  MonitorError,
  MonitorErrorDetails,
  MonitorErrorSource,
  MonitorEvent,
  MonitorSnapshot,
  NetworkEntry,
  NetworkSnapshot,
  PerformanceSnapshot,
  ReactSnapshot,
  ReporterSnapshot,
  ReportFailure,
  WebVitalMetric,
  WebVitalName,
  WebVitalsSnapshot,
} from 'monitor-api';
