export { MonitorPill } from './components/MonitorPill'
export type { MonitorPillProps, MonitorPillScope } from './components/MonitorPill'
export { MonitorInspector } from './components/MonitorInspector'
export type { MonitorInspectorProps } from './components/MonitorInspector'
export { Dashboard } from './components/Dashboard'
export type { DashboardProps } from './components/Dashboard'

export { fpsColor, latencyColor, memoryColor } from './utils/fpsColor'
export { formatBytes, formatMemory, formatTime } from './utils/formatters'
export { toChartData } from './utils/chartData'
export { COLOR_FPS_GOOD, COLOR_FPS_WARN, COLOR_FPS_BAD, COLOR_MEMORY, COLOR_LATENCY, COLOR_EVENTS } from './utils/colors'
